USE GestionIncidencias;

CREATE TABLE IF NOT EXISTS mail_management (
  message_id VARCHAR(255) PRIMARY KEY,
  incidencia_generada BOOLEAN NOT NULL DEFAULT FALSE,
  asignada BOOLEAN NOT NULL DEFAULT FALSE,
  tecnico_asignado VARCHAR(150) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tecnico (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
