USE GestionIncidencias;

CREATE TABLE IF NOT EXISTS mail_management (
  message_id VARCHAR(255) PRIMARY KEY,
  incidencia_generada BOOLEAN NOT NULL DEFAULT FALSE,
  asignada BOOLEAN NOT NULL DEFAULT FALSE,
  tecnico_asignado VARCHAR(150) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tecnico (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  email VARCHAR(255) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS incidencia_inbox (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  message_id VARCHAR(255) NOT NULL,
  mailbox VARCHAR(255) NOT NULL,
  received_date_time VARCHAR(100) NOT NULL,
  sender VARCHAR(255) NOT NULL,
  subject VARCHAR(500) NOT NULL,
  summary VARCHAR(1000) NOT NULL,
  tecnico_asignado VARCHAR(150) NOT NULL,
  tecnico_email VARCHAR(255) NOT NULL,
  categoria_id BIGINT NULL,
  assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_incidencia_inbox_message (message_id)
);

CREATE TABLE IF NOT EXISTS categoria (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  abreviatura VARCHAR(20) NOT NULL,
  UNIQUE KEY uq_categoria_nombre (nombre),
  UNIQUE KEY uq_categoria_abreviatura (abreviatura)
);
